require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ResidentialsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Residential. As you add validations to Residential, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResidentialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all residentials as @residentials" do
      residential = Residential.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:residentials)).to eq([residential])
    end
  end

  describe "GET show" do
    it "assigns the requested residential as @residential" do
      residential = Residential.create! valid_attributes
      get :show, {:id => residential.to_param}, valid_session
      expect(assigns(:residential)).to eq(residential)
    end
  end

  describe "GET new" do
    it "assigns a new residential as @residential" do
      get :new, {}, valid_session
      expect(assigns(:residential)).to be_a_new(Residential)
    end
  end

  describe "GET edit" do
    it "assigns the requested residential as @residential" do
      residential = Residential.create! valid_attributes
      get :edit, {:id => residential.to_param}, valid_session
      expect(assigns(:residential)).to eq(residential)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Residential" do
        expect {
          post :create, {:residential => valid_attributes}, valid_session
        }.to change(Residential, :count).by(1)
      end

      it "assigns a newly created residential as @residential" do
        post :create, {:residential => valid_attributes}, valid_session
        expect(assigns(:residential)).to be_a(Residential)
        expect(assigns(:residential)).to be_persisted
      end

      it "redirects to the created residential" do
        post :create, {:residential => valid_attributes}, valid_session
        expect(response).to redirect_to(Residential.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved residential as @residential" do
        post :create, {:residential => invalid_attributes}, valid_session
        expect(assigns(:residential)).to be_a_new(Residential)
      end

      it "re-renders the 'new' template" do
        post :create, {:residential => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested residential" do
        residential = Residential.create! valid_attributes
        put :update, {:id => residential.to_param, :residential => new_attributes}, valid_session
        residential.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested residential as @residential" do
        residential = Residential.create! valid_attributes
        put :update, {:id => residential.to_param, :residential => valid_attributes}, valid_session
        expect(assigns(:residential)).to eq(residential)
      end

      it "redirects to the residential" do
        residential = Residential.create! valid_attributes
        put :update, {:id => residential.to_param, :residential => valid_attributes}, valid_session
        expect(response).to redirect_to(residential)
      end
    end

    describe "with invalid params" do
      it "assigns the residential as @residential" do
        residential = Residential.create! valid_attributes
        put :update, {:id => residential.to_param, :residential => invalid_attributes}, valid_session
        expect(assigns(:residential)).to eq(residential)
      end

      it "re-renders the 'edit' template" do
        residential = Residential.create! valid_attributes
        put :update, {:id => residential.to_param, :residential => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested residential" do
      residential = Residential.create! valid_attributes
      expect {
        delete :destroy, {:id => residential.to_param}, valid_session
      }.to change(Residential, :count).by(-1)
    end

    it "redirects to the residentials list" do
      residential = Residential.create! valid_attributes
      delete :destroy, {:id => residential.to_param}, valid_session
      expect(response).to redirect_to(residentials_url)
    end
  end

end
